#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="/home/deploy/game-video-tool"
RUNTIME_DIR="/home/deploy/game-video-runtime"
BACKUP_ROOT="/home/deploy/game-video-backups"
TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="${BACKUP_ROOT}/r3-zero-downtime-${TS}"
REPORT="${RUNTIME_DIR}/r3-install-${TS}.report"
ROLLBACK_READY=0

log() {
  printf '[%s] %s\n' "$(date -Is)" "$*"
}

rollback() {
  local exit_code=$?
  if [ "${ROLLBACK_READY}" = "1" ]; then
    log "install failed; restoring nginx/systemd/sudoers backups"
    cp -a "${BACKUP_DIR}/nginx.conf" /etc/nginx/nginx.conf || true
    rm -rf /etc/nginx/conf.d || true
    cp -a "${BACKUP_DIR}/conf.d" /etc/nginx/conf.d || true
    if [ -f "${BACKUP_DIR}/game-video-tool@.service" ]; then
      cp -a "${BACKUP_DIR}/game-video-tool@.service" /etc/systemd/system/game-video-tool@.service || true
    else
      rm -f /etc/systemd/system/game-video-tool@.service || true
    fi
    if [ -f "${BACKUP_DIR}/game-video-zero-downtime" ]; then
      cp -a "${BACKUP_DIR}/game-video-zero-downtime" /etc/sudoers.d/game-video-zero-downtime || true
      chmod 0440 /etc/sudoers.d/game-video-zero-downtime || true
    else
      rm -f /etc/sudoers.d/game-video-zero-downtime || true
    fi
    systemctl daemon-reload || true
    nginx -t && nginx -s reload || true
  fi
  log "FAILED exit_code=${exit_code}"
  exit "${exit_code}"
}
trap rollback ERR

if [ "$(id -u)" != "0" ]; then
  echo "FAILED: must run as root" >&2
  exit 1
fi

mkdir -p "${RUNTIME_DIR}/logs" "${RUNTIME_DIR}/releases" "${RUNTIME_DIR}/slots/57991" "${RUNTIME_DIR}/slots/57992" "${BACKUP_DIR}"
chown -R deploy:deploy "${RUNTIME_DIR}"
if [ ! -f "${RUNTIME_DIR}/active-port" ]; then
  printf '57991' > "${RUNTIME_DIR}/active-port"
fi
chown deploy:deploy "${RUNTIME_DIR}/active-port"

log "backup system config to ${BACKUP_DIR}"
cp -a /etc/nginx/nginx.conf "${BACKUP_DIR}/nginx.conf"
cp -a /etc/nginx/conf.d "${BACKUP_DIR}/conf.d"
if [ -f /etc/systemd/system/game-video-tool@.service ]; then
  cp -a /etc/systemd/system/game-video-tool@.service "${BACKUP_DIR}/game-video-tool@.service"
fi
if [ -f /etc/sudoers.d/game-video-zero-downtime ]; then
  cp -a /etc/sudoers.d/game-video-zero-downtime "${BACKUP_DIR}/game-video-zero-downtime"
fi
ROLLBACK_READY=1

log "install systemd template and switch script"
install -o root -g root -m 0644 "${APP_DIR}/deploy/game-video-tool@.service" /etc/systemd/system/game-video-tool@.service
install -o root -g root -m 0755 "${APP_DIR}/deploy/game-video-switch-upstream.sh" /usr/local/sbin/game-video-switch-upstream
systemctl daemon-reload

log "write nginx upstream include"
cat > /etc/nginx/conf.d/game-video-tool-upstream.inc <<'EOF'
# Generated by zero-downtime install. Updated by game-video-switch-upstream.
set $game_video_backend http://127.0.0.1:57991;
EOF

log "write nginx main config with blue/green backend variable"
cat > /etc/nginx/nginx.conf <<'EOF'
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    types_hash_max_size 4096;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    limit_req_zone $binary_remote_addr zone=login_zone:10m rate=5r/s;

    server {
        listen 80;
        listen [::]:80;
        server_name _;

        include /etc/nginx/conf.d/game-video-tool-upstream.inc;

        client_max_body_size 500m;

        location = /api/auth/login {
            limit_req zone=login_zone burst=20 nodelay;

            proxy_pass $game_video_backend;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 60;
            proxy_send_timeout 60;
        }

        location / {
            proxy_pass $game_video_backend;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 300;
            proxy_send_timeout 300;
        }
    }
}
EOF

log "remove direct backend refs from inactive conf.d compatibility file"
if [ -f /etc/nginx/conf.d/game-video-tool.conf ]; then
  python3 - <<'PY'
from pathlib import Path
path = Path("/etc/nginx/conf.d/game-video-tool.conf")
text = path.read_text(encoding="utf-8", errors="replace")
text = text.replace("proxy_pass http://127.0.0.1:57991;", "proxy_pass $game_video_backend;")
if "include /etc/nginx/conf.d/game-video-tool-upstream.inc;" not in text:
    text = text.replace("server {\n", "server {\n    include /etc/nginx/conf.d/game-video-tool-upstream.inc;\n", 1)
path.write_text(text, encoding="utf-8")
PY
fi

log "install least privilege sudoers"
install -o root -g root -m 0440 "${APP_DIR}/deploy/sudoers-game-video-zero-downtime.example" /etc/sudoers.d/game-video-zero-downtime
visudo -cf /etc/sudoers.d/game-video-zero-downtime

log "test and reload nginx"
nginx -t
nginx -s reload

log "verify active health"
curl -fsS --max-time 5 http://127.0.0.1:57991/health >/dev/null
curl -fsS --max-time 5 http://106.53.49.23/health >/dev/null

log "write report"
{
  echo "SUCCESS"
  echo "backup_dir=${BACKUP_DIR}"
  echo "runtime_dir=${RUNTIME_DIR}"
  echo "active_port=$(cat "${RUNTIME_DIR}/active-port")"
  systemctl show game-video-tool.service -p ActiveState -p MainPID --no-pager
  nginx -t
} > "${REPORT}" 2>&1
chown deploy:deploy "${REPORT}"
chmod 0644 "${REPORT}"

ROLLBACK_READY=0
log "SUCCESS report=${REPORT}"
